name: dotnet build and test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 9.0.306
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build -warnaserror --no-restore
      - name: Test
        run: dotnet run --no-build --project SshCATests/SshCATests.fsproj --summary
