name: dotnet pack and publish

on:
  release:
    types: [ released ]
    branches: [ main ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.0.0
        with:
          dotnet-version: 9.0.306
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: VERSION=${GITHUB_REF##*/} dotnet build -warnaserror --no-restore
      - name: Test
        run: dotnet run --no-build --project SshCATests/SshCATests.fsproj --summary
      - name: Pack
        run: VERSION=${GITHUB_REF##*/} dotnet pack -o . -c Release
      - name: Publish
        run: dotnet nuget push SshCA.*.nupkg -s https://nuget.org -k ${{ secrets.NUGET_API_KEY }}
